apiVersion: v1
data:
  production.toml: |
    [server]
    port = 5000
    host = "0.0.0.0"

    [metrics_server]
    host = "0.0.0.0"
    port = 6128

    [pool_config]
    pool = 2

    [log]
    log_format = "json"
    log_level = "debug"

    [database]
    user = {{ .Values.external.postgresql.config.username }}
    password = {{ .Values.external.postgresql.config.password }}
    host = {{ .Values.external.postgresql.config.host }}
    port = 5432
    dbname = {{ .Values.external.postgresql.config.database }}
    pool_size = 5
    min_idle = 2


kind: ConfigMap
metadata:
  name: keymanager-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
