apiVersion: v1
data:
  production.toml: |
    [server]
    port = 5000
    host = "0.0.0.0"

    [metrics_server]
    host = "0.0.0.0"
    port = 6128

    [pool_config]
    pool = 2

    [log]
    log_format = "json"
    log_level = "debug"

kind: ConfigMap
metadata:
  name: keymanager-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
