apiVersion: v1
data:
  CRIPTA__SECRETS__KMS_CONFIG__KEY_ID: {{ .Values.server.secrets.key_id | b64enc }}
  CRIPTA__SECRETS__KMS_CONFIG__REGION: {{ .Values.server.secrets.region | b64enc }}
  CRIPTA__DATABASE__PASSWORD: {{ include "keymanager-psql.password" . | b64enc }}
kind: Secret
metadata:
  name: keymanager-secrets-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
