apiVersion: v1
kind: Service
metadata:
  labels:
    app: keymanager
  name: keymanager
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: http
  selector:
    app: keymanager
  sessionAffinity: None
  type: ClusterIP
